apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: gcr.io/todo-project-440909/devops-backend:1.0.0
        env:
        - name: DATABASE_URL
          value: "postgres://user:password@postgres-db-service:5432/todoapp"
        - name: JWT_SECRET
          value: "secret-key"
        ports:
        - containerPort: 4400
      imagePullSecrets:
        - name: gcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4400
      targetPort: 4400
  type: LoadBalancer
