apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: kumarshubham16/devops-be:2.2
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          value: "postgres://user:password@postgres-db-service:5432/todoapp"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: jwt_secret
        ports:
        - containerPort: 4400
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4400
      targetPort: 4400
  type: LoadBalancer
