apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: gcr.io/todo-project-440909/devops-frontend:1.0.0
        env:
        - name: REACT_APP_BACKENDHOST
          value: <Backend-LoadBalancer-Ip>
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: gcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web-app-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
