apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: kumarshubham16/devops-fe:latest
        env:
        - name: REACT_APP_HOSTNAME
          value: "backend"
        ports:
        - containerPort: 3000
