apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  #if tls is there
  # tls:
  #   - hosts:
  #       - shubham.it.com
  #     secretName: todo-shubham-tls
  #   - hosts:
  #       - be.shubham.it.com
  #     secretName: be-shubham-tls
  rules:
    - host: shubham.it.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-web-app-service
                port:
                  number: 3000
    - host: be.shubham.it.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-api-service
                port:
                  number: 4400